#
# Build stage
#
FROM maven:3.8.6-openjdk-18 AS build
USER root
WORKDIR /home/app/
COPY . .
RUN mvn  clean package -Dspring-boot.run.profiles=prod

#
# Package stage
#
FROM openjdk:20-slim
USER root
COPY --from=build /home/app/target/controle-financiero-0.0.18-SNAPSHOT.jar /usr/local/lib/
EXPOSE 8082
ENTRYPOINT ["java","-Dspring.profiles.active=prod","-jar","/usr/local/lib/controle-financiero-0.0.18-SNAPSHOT.jar"]

##docker run -d -p 8080:8080 --name ponto-eletronico-java  hugopaul/ponto-eletronico-java
##docker build -t=hugopaul/ponto-eletronico-java .