spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://solidtechsolutions.com.br:5432/controlefinanceiro-prod
    username: postgres
    password: Reisapao123*
    platform: postgres
    driverClassName: org.postgresql.Driver

server:
  servlet:
    context-path: /controle-financeiro-prod
  port: 8082
application:
  security:
    jwt:
      secret-key: 586E3272357538782F413F4428472B4B6250655367566B597033733676397924
      expiration: 10000000
      refresh-token:
        expiration: 1000000